### ISSUE TITLE
Unrelated to this repo but I THINK MY GD ACCOUNT GOT DISABLED

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [CallocGD/GD-2.206-Decompiled#2]
(THIS IS FOR CALLOC AND CALLOC ONLY, IF YOU ARE NOT CALLOC DO NOT READ BELOW THIS LINE)

I can't DM you in GD so I have to post an issue on one of your GitHub repos...

My username is BombCraft2010. I am a 14 year old autistic Geometry Dash player and creator, and I am currently trying to beat Acu as my first extreme and am also working on a level called Gather The Gloinks, a TADC-inspired platformer that would be my 7th rateworthy level (none of the 6 I've uploaded are rated), and I have a problem.

1 hour and 45 minutes ago, I received an email from a GD friend with a video where he opened my account and found no profile posts, levels, or comments (although my stats remain: 3990 stars, 230 moons, 120 secret coins, 342 user coins, 89 demons, and 0 CP)

When I saw the email, I logged onto GD and he was right: my levels are gone, my comments are gone, I can't upload levels or comment, daily chests don't work, and I can't view others' profiles (or my own...)

Strangely, my lists are still on the servers, but I can't upload any more lists.

I suspect this is due to the kinds of levels I upload; most of my 1.1K+ levels are shitposts, often involving sex jokes (e.g. a recent level called "my waifu list" which showed a few different fictional characters I want to fuck (such as Husk from Hazbin Hotel)), however none of my 1.1K+ levels are actually NSFW; while I have uploaded many levels claiming to be porn (e.g. "Adrian Agreste R34", yes that's an actual level I uploaded), none of these levels contained actual porn beyond a bunch of crudely drawn penises made out of normal faces.

It might also be because this morning I uploaded three levels hating on Hatsune Miku:
The first was called "kys sasaki wataru" and its contents were a button that you had to press to kill Hatsune Miku (there's no blood)
The second was called "OddMod" and it literally just told GD creator OddMod to kill herself because she made a Hatsune Miku-themed insane demon called "MikuMikuMikuMiku"
The third was called "Why 2006 was best year" or smth like that and it just said that 2006 was the best year because Hatsune Miku was invented in 2007. (ignore the fact that I was born in 2010)

Can you help me get unbanned?

**Comment by CallocGD** [comment]
@ImmediateMurderProfessionals Unfortunately this question is a little off-topic. All I can really say is my famous quote, "Ask Robtop" otherwise I would ask an eldermod to release you from your silence since it doesn't seem like you did anything wrong. This is not the place to ask for these kind of questions and like I said before. Ask an Eldermod for help.

**Comment by ImmediateMurderProfessionals** [comment]
Ok

**Comment by ImmediateMurderProfessionals** [comment]
I’ll try to convince my parents to let me get discord
